FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

EXPOSE 5173

# Em vez de buildar e usar Nginx, rodamos o Vite direto
CMD ["npm", "run", "dev", "--", "--host"]
