services:

  backend:
      build: ./backend
      ports:
        - "5000:5000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  database:
    image: postgres:16
    environment:
      POSTGRES_DB: db-system
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
