"""initial migration

Revision ID: 8a6c5c0e98fd
Revises: 
Create Date: 2026-03-02 13:23:30.287943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a6c5c0e98fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_client',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpf_cliente', sa.String(), nullable=False),
    sa.Column('rg_cliente', sa.String(), nullable=False),
    sa.Column('nome_cliente', sa.String(), nullable=False),
    sa.Column('nasc_cliente', sa.String(), nullable=True),
    sa.Column('tele_pessoal_cliente', sa.String(), nullable=True),
    sa.Column('email_cliente', sa.String(), nullable=False),
    sa.Column('senha_cliente', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_dispatcher',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpf_desp', sa.String(), nullable=False),
    sa.Column('rg_desp', sa.String(), nullable=False),
    sa.Column('nome_desp', sa.String(), nullable=False),
    sa.Column('nasc_desp', sa.String(), nullable=True),
    sa.Column('tele_pessoal_desp', sa.String(), nullable=True),
    sa.Column('email_desp', sa.String(), nullable=False),
    sa.Column('senha_desp', sa.String(), nullable=False),
    sa.Column('regis_crdd', sa.String(), nullable=False),
    sa.Column('data_exp_regis', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_dispatcher')
    op.drop_table('user_client')
    # ### end Alembic commands ###
